services:
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend_portfolio
    restart: unless-stopped
    ports:
      - "3010:80"
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend_portfolio
    restart: unless-stopped
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    depends_on:
      mongo:
        condition: service_healthy
    networks:
      - backend_zone
    healthcheck:
      test: ["CMD-SHELL", "npm run start"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
  mongo:
    image: mongo:8
    container_name: mongodb
    restart: unless-stopped
    ports:
      - "27018:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: dev
      MONGO_INITDB_ROOT_PASSWORD: "123456"
      
    volumes:
      - mongo_data:/data/db
    networks:
      - backend_zone
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "mongosh --quiet --host localhost --port 27017 --username \"$${MONGO_INITDB_ROOT_USERNAME}\" --password \"$${MONGO_INITDB_ROOT_PASSWORD}\" --authenticationDatabase admin --eval \"quit(db.adminCommand('ping').ok ? 0 : 2)\""
        ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
volumes:
  mongo_data:
networks:
  backend_zone: 